### ISSUE TITLE
Infusing?

### ISSUE THREAD

**Issue by milkev** [TeamSuperPeople/azuma#6]
![image](https://user-images.githubusercontent.com/22010128/78746739-df475900-7924-11ea-821a-ae5013a49c66.png)
so uh... is it supposed to just be still like this? this is what the book says to do and i have more enough mana. i could make the first tier items (like mana iron) perfectly fine.

**Comment by Ljime** [comment]
Hello there, thank you for your concerns. Our developers have looked at this issue and it will be solved soon. Apparently, one of our developers (not me) mistook blaze rod for blaze powder when doing the book recipes. This will be quickly resolved, thank you for bringing attention to this issue.

**Comment by Draylar** [comment]
Fixed in [1.2.5](https://github.com/TeamSuperPeople/azuma/releases/tag/1.2.5-beta-1.15.2). Thanks for the report!

_Note: the actual recipe is 1 nether bricks (block), 1 blaze powder, and the rest as you have it. The book has just been updated to reflect this._
