### ISSUE TITLE
Resource pack compat issue

### ISSUE THREAD

**Issue by Xogue** [TeamSuperPeople/azuma#8]
When the better faithful resource pack is applied, the Azuma book looks like the images below. I have another pack that directly changes the font (Xogue V2.2 (Slim)) and when it is applied by itself, this doesn't happen.

I can upload the resource pack if you have somewhere I can upload it to. I don't remember exactly where I got it. Not sure if it matters or not.

![image](https://user-images.githubusercontent.com/1455817/84190053-476d0500-aa64-11ea-8ee4-fc64ee79d2fa.png)

![image](https://user-images.githubusercontent.com/1455817/84190076-518f0380-aa64-11ea-9370-0071685b8751.png)

![image](https://user-images.githubusercontent.com/1455817/84189824-e6453180-aa63-11ea-93b4-486bbd518f25.png)

**Comment by Draylar** [comment]
This is an issue with [Patchouli](https://github.com/Vazkii/Patchouli) (although it's not Patchouli's fault). There's an existing issue about it [here](https://github.com/Vazkii/Patchouli/issues/236).

edit: other issues show that this is a problem with Faithful.
